from torchvision.models import (
    alexnet,
    densenet121,
    densenet161,
    densenet169,
    densenet201,
    googlenet,
    inception_v3,
    mnasnet0_5,
    mnasnet0_75,
    mnasnet1_0,
    mnasnet1_3,
    mobilenet_v2,
    mobilenet_v3_large,
    mobilenet_v3_small,
    resnet18,
    resnet34,
    resnet50,
    resnet101,
    resnet152,
    resnext50_32x4d,
    resnext101_32x8d,
    shufflenet_v2_x0_5,
    shufflenet_v2_x1_0,
    shufflenet_v2_x1_5,
    shufflenet_v2_x2_0,
    squeezenet1_0,
    squeezenet1_1,
    vgg11,
    vgg13,
    vgg16,
    vgg19,
    wide_resnet50_2,
    wide_resnet101_2,
)

from code_soup.common.vision.models.allconvnet import AllConvNet
from code_soup.common.vision.models.nin import NIN
from code_soup.common.vision.models.simple_cnn_classifier import SimpleCnnClassifier
