name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Caching Linux
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Setup
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov codecov
          pip install parameterized
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Tests
        run: pytest --cov-report xml --cov='./code_soup/' --cov-config=.coveragerc

      - name: Code Coverage Report
        uses: codecov/codecov-action@v1
        if: always()
        with:
          fail_ci_if_error: false
          file: coverage.xml
          env_vars: OS,PYTHON
